version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: typescript
    versions:
    - 3.9.7
    - 3.9.8
  - dependency-name: "@vue/cli-plugin-typescript"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
